name: EPG Pluto it

on:
  # Trigger manuale
  workflow_dispatch:

jobs:
  run-epg-pluto-it:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run EPG Pluto it
        env:
          REGION: ${{ secrets.IT_KEY }}
        run: python epg_pluto_it.py
          
      - name: Commit generated EPG and Log files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated EPG Update"
          file_pattern: 'epg_pluto_it.xml channel_list.txt'
          branch: main 
